### ISSUE TITLE
can't add as gold

### ISSUE THREAD

**Issue by unhammer** [apertium/apertium-regtest#11]
```
 apertium-regtest -p 3333 web
Starting server
Open http://localhost:3333 in your browser
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 57376)
Traceback (most recent call last):
  File "/usr/lib/python3.8/socketserver.py", line 683, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/bin/apertium-regtest", line 649, in __init__
    super().__init__(request, client_address, server, directory=directory)
  File "/usr/lib/python3.8/http/server.py", line 647, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/lib/python3.8/socketserver.py", line 747, in __init__
    self.handle()
  File "/usr/lib/python3.8/http/server.py", line 427, in handle
    self.handle_one_request()
  File "/usr/lib/python3.8/http/server.py", line 415, in handle_one_request
    method()
  File "/usr/bin/apertium-regtest", line 662, in do_POST
    self.do_callback(urllib.parse.parse_qs(data.decode('utf-8')))
  File "/usr/bin/apertium-regtest", line 743, in do_callback
    Corpus.all_corpora[corp].set_gold(hsh, golds, stp)
  File "/usr/bin/apertium-regtest", line 556, in set_gold
    blob = self.step(step)
  File "/usr/bin/apertium-regtest", line 472, in step
    return self.data['cmds'][self.commands.get(s, -1)]
KeyError: 'cmds'
----------------------------------------

```

**Comment by unhammer** [comment]
wait now it works again i have no idea why
